name: PR creation for main branch
on:
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: notify PR creation
        run: |
          echo "A pull request has been created targeting the main branch(master)"
    
    
